import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Building2, Users, Target, ArrowDownToLine, Loader2 } from 'lucide-react';
import html2pdf from 'html2pdf.js';

const WhyISUC = () => {
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  const generatePDF = () => {
    setIsGeneratingPdf(true);
    
    // Create a clean, simple layout for the PDF to avoid alignment issues
    const element = document.createElement('div');
    element.innerHTML = `
      <div style="padding: 40px; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #1e293b; line-height: 1.6;">
        <div style="text-align: center; margin-bottom: 40px;">
          <h1 style="color: #0f172a; font-size: 36px; margin-bottom: 10px; font-weight: bold;">ISUC-2026 Overview</h1>
          <h3 style="color: #64748b; font-size: 20px; margin-top: 0; font-weight: normal;">Indo-Saudi Umrah Connect</h3>
        </div>
        
        <hr style="margin: 30px 0; border: 0; border-top: 2px solid #e2e8f0;" />
        
        <div style="margin-bottom: 30px;">
          <h2 style="color: #1a1a1a; font-size: 24px; border-left: 4px solid #b68d40; padding-left: 15px; margin-bottom: 15px;">Event Mission</h2>
          <p style="font-size: 16px; color: #454545;">India is the fastest-growing Umrah market globally, sending over 1.8M pilgrims in 2025. ISUC-2026 perfectly bridges the gap between Saudi suppliers and Indian operators.</p>
        </div>
        
        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 24px; border-left: 4px solid #f59e0b; padding-left: 15px; margin-bottom: 15px;">Tour Schedule (July 3-9, 2026)</h2>
          <ul style="font-size: 16px; color: #475569; padding-left: 20px;">
            <li style="margin-bottom: 10px;"><strong>Delhi (3-5 July):</strong> North India Market Entry</li>
            <li style="margin-bottom: 10px;"><strong>Mumbai (5-7 July):</strong> West India Core Hub</li>
            <li style="margin-bottom: 10px;"><strong>Hyderabad (7-8 July):</strong> South Central Dominance</li>
            <li style="margin-bottom: 10px;"><strong>Chennai (8-9 July):</strong> Deep South Gateway</li>
          </ul>
        </div>

        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 24px; border-left: 4px solid #f59e0b; padding-left: 15px; margin-bottom: 15px;">Why Attend?</h2>
          <ul style="font-size: 16px; color: #475569; padding-left: 20px;">
            <li style="margin-bottom: 15px;"><strong>For Saudi Suppliers:</strong> Direct access to the top OTAs controlling 70% of the volume across 4 cities.</li>
            <li style="margin-bottom: 15px;"><strong>For Indian Buyers:</strong> Meet 40+ premium Saudi DMCs, Hotels, and Transport companies. Contract direct for better rates.</li>
            <li style="margin-bottom: 15px;"><strong>For Sponsors:</strong> Own the conversation between Saudi and India's Umrah trade.</li>
          </ul>
        </div>

        <div style="margin-bottom: 30px;">
          <h2 style="color: #0f172a; font-size: 24px; border-left: 4px solid #f59e0b; padding-left: 15px; margin-bottom: 15px;">Exhibitor Inclusions</h2>
          <p style="font-size: 16px; color: #475569;">Fully managed 6-Day tour including Premium 5-Star Hotels, Domestic Flights, All Meals, and Dedicated Transfers.</p>
        </div>
        
        <div style="margin-top: 60px; text-align: center; color: #94a3b8; font-size: 14px; border-top: 1px solid #e2e8f0; padding-top: 20px;">
          <p>Generated by ISUC-2026 | www.indo-saudi-umrah-connect.com</p>
        </div>
      </div>
    `;
    
    const opt = {
      margin:       0.5,
      filename:     'ISUC-2026-Overview.pdf',
      image:        { type: 'jpeg', quality: 0.98 },
      html2canvas:  { scale: 2 },
      jsPDF:        { unit: 'in', format: 'letter', orientation: 'portrait' }
    };

    html2pdf().set(opt).from(element).save().then(() => {
      setIsGeneratingPdf(false);
    }).catch((err) => {
      console.error("PDF generation failed:", err);
      setIsGeneratingPdf(false);
    });
  };

  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2
      }
    }
  };

  const itemVariants = {
    hidden: { y: 30, opacity: 0 },
    visible: {
      y: 0,
      opacity: 1,
      transition: { duration: 0.6, ease: "easeOut" }
    }
  };

  return (
    <section id="why" className="py-16 bg-secondary-900 relative overflow-hidden">
      {/* Decorative background blobs */}
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-primary-500/10 rounded-full blur-3xl -translate-y-1/2 translate-x-1/2"></div>
      <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-accent-500/10 rounded-full blur-3xl translate-y-1/2 -translate-x-1/2"></div>

      <div className="container mx-auto px-4 relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <motion.h2 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="text-3xl md:text-4xl font-display font-bold text-white mb-6"
          >
            Why India. Why Now. <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-400 to-accent-300">Why ISUC.</span>
          </motion.h2>
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.1 }}
            className="text-lg text-secondary-400"
          >
            India is the fastest-growing Umrah market globally. Here is how ISUC-2026 bridges the gap between Saudi suppliers and Indian operators.
          </motion.p>
        </div>

        <motion.div 
          variants={containerVariants}
          initial="hidden"
          whileInView="visible"
          viewport={{ once: true }}
          className="grid md:grid-cols-3 gap-8 mb-16"
        >
          {/* Card 1 */}
          <motion.div variants={itemVariants} className="bg-secondary-900 rounded-3xl p-8 group hover:-translate-y-3 transition-all duration-500 relative overflow-hidden shadow-xl hover:shadow-2xl">
            <div className="absolute inset-0 z-0">
              <img src="/assets/nano_why_suppliers.png" alt="Saudi Suppliers" className="w-full h-full object-cover opacity-30 group-hover:opacity-40 group-hover:scale-110 transition-all duration-700" />
              <div className="absolute inset-0 bg-gradient-to-t from-secondary-900 via-secondary-900/90 to-secondary-900/60 transition-all duration-500 group-hover:from-secondary-900 group-hover:via-secondary-900/80 group-hover:to-secondary-900/50"></div>
            </div>
            <div className="relative z-10">
              <div className="w-14 h-14 bg-primary-500/20 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-primary-500 transition-all duration-500 border border-primary-500/30 shadow-lg">
                <Building2 className="w-7 h-7 text-primary-400 group-hover:text-white transition-colors" />
              </div>
              <h3 className="text-2xl font-display font-bold text-white mb-4">For Saudi Suppliers</h3>
              <p className="text-secondary-300 leading-relaxed mb-4 font-medium">
                India sent <strong className="text-primary-400">1.8M+ pilgrims</strong> for Umrah in 2025. But 70% of volume is controlled by &lt;50 B2B operators you can't reach on email.
              </p>
              <p className="font-semibold text-white bg-primary-500/20 p-3 rounded-lg border border-primary-500/30 backdrop-blur-sm">
                ISUC-2026 puts them across your table.
              </p>
            </div>
          </motion.div>

          {/* Card 2 */}
          <motion.div variants={itemVariants} className="bg-secondary-900 rounded-3xl p-8 group hover:-translate-y-3 transition-all duration-500 relative overflow-hidden shadow-xl hover:shadow-2xl border-primary-100/50">
            <div className="absolute inset-0 z-0">
              <img src="/assets/nano_why_buyers.png" alt="Indian Buyers" className="w-full h-full object-cover opacity-30 group-hover:opacity-40 group-hover:scale-110 transition-all duration-700" />
              <div className="absolute inset-0 bg-gradient-to-t from-secondary-900 via-secondary-900/90 to-secondary-900/60 transition-all duration-500 group-hover:from-secondary-900 group-hover:via-secondary-900/80 group-hover:to-secondary-900/50"></div>
            </div>
            <div className="relative z-10">
              <div className="w-14 h-14 bg-accent-500/20 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-accent-500 transition-all duration-500 border border-accent-500/30 shadow-lg">
                <Users className="w-7 h-7 text-accent-400 group-hover:text-secondary-900 transition-colors" />
              </div>
              <h3 className="text-2xl font-display font-bold text-white mb-4">For Indian Buyers</h3>
              <p className="text-secondary-300 leading-relaxed mb-4 font-medium">
                Meet <strong className="text-accent-400">40+ premium Saudi DMCs, Hotels, Transport & Tech companies</strong> in your city. Contract direct. Better rates. New products for 2026 season.
              </p>
              <p className="font-semibold text-white bg-accent-500/20 p-3 rounded-lg border border-accent-500/30 backdrop-blur-sm">
                No exhibition crowds. Just business.
              </p>
            </div>
          </motion.div>

          {/* Card 3 */}
          <motion.div variants={itemVariants} className="bg-secondary-900 rounded-3xl p-8 group hover:-translate-y-3 transition-all duration-500 relative overflow-hidden shadow-xl hover:shadow-2xl">
            <div className="absolute inset-0 z-0">
              <img src="/assets/nano_why_sponsors.png" alt="For Sponsors" className="w-full h-full object-cover opacity-30 group-hover:opacity-40 group-hover:scale-110 transition-all duration-700" />
              <div className="absolute inset-0 bg-gradient-to-t from-secondary-900 via-secondary-900/90 to-secondary-900/60 transition-all duration-500 group-hover:from-secondary-900 group-hover:via-secondary-900/80 group-hover:to-secondary-900/50"></div>
            </div>
            <div className="relative z-10">
              <div className="w-14 h-14 bg-primary-600/20 rounded-xl flex items-center justify-center mb-6 group-hover:scale-110 group-hover:bg-primary-600 transition-all duration-500 border border-primary-600/30 shadow-lg">
                <Target className="w-7 h-7 text-primary-400 group-hover:text-white transition-colors" />
              </div>
              <h3 className="text-2xl font-display font-bold text-white mb-4">For Sponsors</h3>
              <p className="text-secondary-300 leading-relaxed mb-4 font-medium">
                <strong className="text-primary-400">Own the conversation</strong> between Saudi & India's Umrah trade. Title Partner branding across 4 cities + 600+ targeted meetings.
              </p>
              <p className="font-semibold text-white bg-primary-600/20 p-3 rounded-lg border border-primary-600/30 backdrop-blur-sm">
                This becomes your annual India pipeline.
              </p>
            </div>
          </motion.div>
        </motion.div>

        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="text-center"
        >
          <button 
            onClick={generatePDF}
            disabled={isGeneratingPdf}
            className="inline-flex items-center gap-2 px-8 py-4 bg-white/10 hover:bg-white/20 border border-white/20 text-white font-semibold rounded-xl transition-all shadow-lg hover:shadow-xl hover:-translate-y-1 disabled:opacity-70 disabled:hover:translate-y-0 disabled:cursor-not-allowed backdrop-blur-sm"
          >
            {isGeneratingPdf ? (
              <>
                <Loader2 className="w-5 h-5 animate-spin" />
                Generating PDF...
              </>
            ) : (
              <>
                <ArrowDownToLine className="w-5 h-5" />
                Download ISUC-2026 Overview PDF
              </>
            )}
          </button>
        </motion.div>

        {/* Social Proof area (as requested by user) */}
        <motion.div 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          viewport={{ once: true }}
          transition={{ delay: 0.4 }}
          className="mt-24 pt-12 border-t border-white/10"
        >
          <p className="text-center text-sm font-semibold text-secondary-500 uppercase tracking-wider mb-8">
            Confirmed Exhibitors Include
          </p>
          <div className="flex justify-center items-center hover:opacity-100 transition-all duration-500 max-w-4xl mx-auto opacity-80">
            <motion.img 
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: 0.6 }}
              src="/assets/logos_collage.png" 
              alt="Premium Partners and Exhibitors" 
              className="w-full h-auto rounded-2xl shadow-2xl border border-white/10"
            />
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default WhyISUC;
